# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"relu": "Activations.ipynb",
         "ReLU": "Activations.ipynb",
         "LeakyReLU": "Activations.ipynb",
         "leaky_relu": "Activations.ipynb",
         "Mish": "Activations.ipynb",
         "mish": "Activations.ipynb",
         "get_activation": "Activations.ipynb",
         "__activations__": "Activations.ipynb",
         "__inputDimError__": "Layers.ipynb",
         "Dense": "Layers.ipynb",
         "Data": "data.ipynb",
         "TrainData": "data.ipynb",
         "TestData": "data.ipynb",
         "create_db": "data.ipynb"}

modules = ["activations.py",
           "layers.py",
           "data.py"]

doc_url = "https://sachinruk.github.io/keraTorch/"

git_url = "https://github.com/sachinruk/keraTorch/tree/master/"

def custom_doc_links(name): return None
